
use customerDB
select * from Customer

--Q1. What is the total revenue generated by male vs. female customers?
	select gender,sum(purchase_amount) "Total Rvenue"  
			from customer
			group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
	select customer_id,purchase_amount 
			from Customer 
			where discount_applied='Yes'	
				and purchase_amount >(select avg(purchase_amount) from customer)


-- Q3. Which are the top 5 products with the highest average review rating?
		select top 5 item_purchased,round(avg(review_rating),2) Average_Review_Rating 
			  from customer 
			  group by item_purchased  
			  order by avg(review_rating) desc

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
	select shipping_type,avg(purchase_amount) 'Average Amount' from customer 
		where shipping_type in ('Standard','Express')
	group by shipping_type

	
--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
	select  subscription_status,
			count(customer_id) as total_cust,
			avg(purchase_amount) as avg_amount,
			sum(purchase_amount) as total_revenue
		from customer
		group by subscription_status

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
	select top 5 item_purchased,
			round(100.0*sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_rate
			from customer
			group by item_purchased
			order by round(100.0*sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) desc
			


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with cte
as 
(
select case when previous_purchases=1 then 'New'
			when previous_purchases between 2 AND 10  then 'Returning'
			else 'Loyal'
			end as cust_segment
		from Customer
)
select cust_segment,count(cust_segment) Total_cust from cte group by cust_segment

--Q8. What are the top 3 most purchased products within each category? 
  with cte
  as
  (
	select category,
			item_purchased,
			count(customer_id) total_orders ,
		    row_number() over(partition by category order by count(customer_id) desc) num
	 from Customer group by category,item_purchased 
  )
	select category,item_purchased,total_orders from cte where num<=3

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
	select subscription_status, count(customer_id) total_cust_with_more_than_5_previous_purchase from customer
	where previous_purchases>5
	group by subscription_status

	
--Q10. What is the revenue contribution of each age group? 
select age_group,sum(purchase_amount) Revenue_contribution
	from customer
	group by age_group
	order by sum(purchase_amount) desc

